---
- name: add ssh key
  authorized_key:
    user: borg
    state: present
    key: "{{ lookup('file', 'roles/add_ssh/files/id_rsa.pub')}}"

- name: template sshd config
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"

#- name: template ssh user config
#  template:
#    src: templates/config
#    dest: /home/vagrant/.ssh/
#    owner: vagrant
#    mode: "0400"
#  become: no

- name: restart sshd
  systemd:
    name: sshd
    state: restarted

