---
- name: add ssh key
  authorized_key:
    user: borg
    state: present
    key: "{{ lookup('file', 'roles/add_ssh/files/id_rsa.pub')}}"

#- name: template sshd config
#  template:
#    src: templates/sshd_config.j2
#    dest: /etc/ssh/sshd_config
#    owner: root
#    group: root
#    mode: "0644"

- name: restart sshd
  systemd:
    name: sshd
    state: restarted

