---
- name: create user borg
  user:
    name: borg
    createhome: yes
    state: present
    
- name: create dir for backup
  file:
    path: /var/backup
    state: directory
    owner: borg
    group: borg

- name: create ssh dir
  file:
    path: /home/borg/.ssh
    state: directory
    mode: "0700"

- name: create authorized_keys
  file: 
    path: /home/borg/.ssh/authorized_keys
    state: touch
    mode: "0600"
    


