---
- name: borgbackup init repo
  shell:
    cmd: borg init -e=none borg@192.168.56.66:/var/backup
  ignore_errors: true

- name: template systemd units borg
  template:
    src: templates/borg-backup.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: "0644"

- name: template systemd units borg
  template:
    src: templates/borg-backup.timer
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: "0644"    

- name: start systemd timer   
  systemd: 
    name: "{{ item }}"
    enabled: yes
    state: started
    daemon_reload: yes
  with_items:
    - borg-backup.service
    - borg-backup.timer  


- name: list backup
  shell:
    cmd: journalctl -u borg-backup.service
  register: result